name: ${project.name}
main: com.poixson.roads.RoadsPlugin
version: ${project.version}
api-version: ${spigot-short-version}
depend:
  - pxnCommonPluginMC
authors: [ lorenzop ]
website: ${project.url}
description: ${project.description}
commands:
    roads:
        description: "Create roads as you walk"
        usage: "Usage: /roads <cmd>"
permission-message: "You don't have permission to use this command."
permissions:
    roads.*:
        default: op
        description: Gives access to all roads commands
        children:
            roads.start: true
            roads.stop:  true
    roads.start:
        default: op
        description: Start making roads
    roads.stop:
        default: op
        description: Stop making roads
